package.json, src/chatTab.ts, src/extension.ts, src/rconsoleCommands.ts, src/rconsoleProvider.ts
Enables chat in the comment bar and lets the chat to be sent to the sidebar
=> Toolbox2 messages in thread

package.json, src/extension.ts, src/rconsoleCommands.ts, src/rconsoleProvider.ts
Reverts smallcloudai/refact-vscode#52
=> Revert "Revert "Toolbox2 messages in thread""

src/rconsoleCommands.ts, src/rconsoleProvider.ts
when the console chat is open clicking the hints should run the command.
=> WIP: add click handlers to command hints

src/chatTab.ts, src/fetchAPI.ts, src/statisticTab.ts
Adds "fill in the middle" to statistics,
Also: I needed to update the chatTab.ts file because it was out-dated in this branch
=> Statistic tab fim

src/chatTab.ts, src/estate.ts, src/rconsoleCommands.ts, src/rconsoleProvider.ts
TODO
[x] Figure out how to scroll to the. comment after the diff has appeared 
[x] Decide if the comment should be above or below the diff
=> WIP: Fix: comment console placement after diff

assets/sidebar.css, assets/sidebar.js, package.json, src/completionProvider.ts, src/extension.ts, src/fetchAPI.ts, src/fimDebug.ts, src/launchRust.ts, src/sidebar.ts
TODO:
[x] Back button
[x] confirm the type defs form the lsp
[x] make it look nice
=> WIP: Fim debug

package.json, src/chatTab.ts
Adds an event handler for preview files
TODO:
[ ] publish a new chat version from at least this commit https://github.com/smallcloudai/refact-chat-js/pull/10/commits/48944e5e50c63f63c3491304cd93b594981377fe
=> Chat preview file request

package.json
Needs this lsp branch to run https://github.com/smallcloudai/refact-lsp/tree/at-commands-ux
=> chore: update chat for testing lsp branch at-commands-ux

package.json
Add a similar message to the one in JetBrains about the vecdb and ast settings.
TODO:
[ ] confirm the link parameters are correct.
=> update ast and vecdb settings messages

package.json, src/chatHistory.ts, src/chatTab.ts, src/fetchAPI.ts, src/rconsoleProvider.ts, src/sidebar.ts
TODO: 
[ ] maybe add tools to the chat requests from the toolbar 
[x] run this with the main version of the lsp that doesn't have tools available.
[x] publish a new version of chat
=> Chat functions

package.json, src/sidebar.ts
TODO: publish a compatible version of chat after this PR https://github.com/smallcloudai/refact-chat-js/pull/69
=> feat: add setting for using shift plus enter to submit chat.

src/sidebar.ts
Works with this branch / pr https://github.com/smallcloudai/refact-chat-js/pull/122
=> feat(pin messages)

package.json, src/interactiveDiff.ts
Fixes the diff on chars by incrementing the counters when lines have been unchanged.
Related to: https://github.com/smallcloudai/refact-vscode/pull/139
issue: https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=78205745
=> Diffs char colours

package.json, src/codeLens.ts
Adds a setting to enable / disable code lenses
=> feaT(codeLens setting): add a setting to enable / disable code lens.

src/sidebar.ts
Relies on https://github.com/smallcloudai/refact-chat-js/pull/162
=> Feature: Focusing on editor in IDE on Escape press

src/codeLens.ts
- Problem: Previously, `Open Chat` was only opening a new chat instead of selecting some code as well (since codelens are attached to functions/methods)
- Solution: Selection of lines of code in prefetched range and then opening a new chat.
- [Open Chat link doesn't attach the code the codelens refers to](https://refact.fibery.io/Software_Development/Task/Open-Chat-link-doesn't-attach-the-code-the-codelens-refers-to-270)
- Step 1: Open a file in IDE which language is supported with CodeLens
- Step 2: Try to click `Open Chat`
- Step 3: Line selection should be revealed and attached inside of the UI
=> Feature: Open Chat instruction selects its code snippet

src/sidebar.ts
Relies on this pull request -> https://github.com/smallcloudai/refact-chat-js/pull/166
=> Fix: Renaming of existing actions

README.md
Added a download link for the VS Code extension to make it easier for users to access the tool.
Let me know if there are any suggestion
Closes #133
=> Chore: Addition of VSCode Marketplace link in README.md

src/chatTab.ts, src/sidebar.ts
[Integrations icons not loading](https://refact.fibery.io/Software_Development/Sprint-2025-02-10-495#Task/Integrations-icons-not-loading-833)
=> Fix: Allow localhost hostnames for CSP

package.json
update for this PR: https://github.com/smallcloudai/refact-chat-js/pull/320
=> update(chat-js): rename "initial setup" to "login page".

.github/workflows/build.yml, .github/workflows/publish.yml, README.md, package.json
=> Version bump 190225

src/sidebar.ts
Keeps the indent on selected code sent to / from the editor
=> feat: keep indent for selected snippet.

package.json, src/extension.ts, src/sidebar.ts
relies on: https://github.com/smallcloudai/refact/pull/644
=> add attach file menu option

src/launchRust.ts
renamings:
code_chat_models -> chat_models
code_chat_default_model -> chat_default_model
=> Fix: Tooltip error not changing

assets/custom-theme.css, src/chatTab.ts
Depends on Tools on/off feature branch
https://github.com/smallcloudai/refact/pull/775
=> fix: overriding background/foreground color for all elements except Tooltip-related & removed ToolCommand since it's no longer exposed

.vscode/launch.json, src/codeLens.ts, src/fetchAPI.ts, src/sidebar.ts
This will compile, although some features like codeLens may not work.
=> WIP: Flexus migration
