src/rconsoleProvider.ts
Issue: console chats aren't initially saved when opened in the sidebar.
to recreate: open console chat, run a command, move to side bar, press back button (or open tab)
=> fix a bug. where the console chat isn't saved in the history

src/chatTab.ts
Given a new chat has been opened in a new tab, when asking questions the sidebar is not updated.
Open a new chat from the side panel, click `open tab`, ask the first question... (the chat history), click on another question and then back to see the new question in the history.
=> fix: update chat history in the side bar when asking a new question from a tab

src/rconsoleCommands.ts, src/rconsoleProvider.ts
Fixes a bug in the chat-console, where when running multiple commands the context file is lost.
To recreate 
Highlight text, press F1, type `/explain`, then type `/improve`
=> fix: multiple commands loses history

.vscode/settings.json, src/chatTab.ts
Set up selfhosted, chat with a model, remove the model then open the toolbox to see an error.
update global caps by calling `global.rust_binary_blob?.read_caps()` to the saved model from the chat can be validated against the most recent caps.
Small bug when opening and close the same chat tab.
=> V1.2 Chat and toolbox model bugs

package.json, src/extension.ts, src/sidebar.ts
duplicate of https://github.com/smallcloudai/refact-vscode/pull/100 but targeting shared-chat-lib branch.
[x] opening chat with hot key
[x] moving away from side bar and pressing hot-key to re-open
=> Shared chat lib hot key fix

src/completionProvider.ts
Fixes an issue where completions are added to the toolbox 
Open toolbox type `/help` and see a completion.
This disables inline completions if the document is a comment
=> fix(toolbox): disable lsp completion when writing in toolbox

src/chatTab.ts
Adding a new line at the start has fixed the first three characters being removed from the diff.
Still todo: handling indentation and partially selected lines
=> WIP: fix: add new lines to start and end of code block

assets/sidebar.css, src/sidebar.ts
Completes
https://github.com/orgs/smallcloudai/projects/5/views/1?pane=issue&itemId=58966966
=> ui(hotkey): remove superscript, normal font-size and slightly opaque

package.json, src/interactiveDiff.ts, src/sidebar.ts
Updated diff library, and set `ignoreWhitespace` and `newlineIsToken` to true
Before:
https://github.com/user-attachments/assets/80aa8e56-26b0-4220-9d23-28d364dd3fb6
After:
https://github.com/user-attachments/assets/36ed915e-f518-4b3f-b1aa-d531d849350c
=> fix(diff): stop adding empty lines to diff

package.json, src/sidebar.ts
relies on https://github.com/smallcloudai/refact-chat-js/pull/139
=> fix(patch apply): it should apply changes through the ide.

src/fetchAPI.ts
Related to https://github.com/smallcloudai/refact-chat-js/pull/142
=> chore(diff-api): remove diff-api calls from fetch and type imports from chat.

src/sidebar.ts
How to recreate the issue.
+ close chat
+ restart vsscode
+  open sidebar.ts in refact-vscode
+ open chat.
=> fix: escape all </script> tags in chats initial state

package.json, src/chatTab.ts, src/codeLens.ts, src/extension.ts, src/fetchAPI.ts, src/launchRust.ts, src/quickProvider.ts, src/sidebar.ts
- Problem: CodeLens in VSCode were lacking of actual chat state, chat window was not opening as expected
- Solution: Added a handler to get current page from `refact-chat-js`, fixed issue with file attachment, actual code selection and formatting. Added multiple checks to control chat's behavior in different scenarios
- [Any background context or related links?](https://github.com/orgs/smallcloudai/projects/5/views/1?filterQuery=alashchev&pane=issue&itemId=82882638)
- Edit your `customization.yaml`, set in every code_lens instruction of `auto_submit` to `false`
- Try to click "Explain" within the code editor's fragment of code
- Chat should open up a new window and paste the snippet from `customization.yaml` and place it in a text area.
- Relies on …
=> Fix: CodeLens workflow

src/codeLens.ts, src/extension.ts, src/sidebar.ts
Fixes file attachment in CodeLens instructions & prevents CodeLens to be sent multiple times by exposing `isStreaming` from `refact-chat-js`
To test out, use `wip/codelens-timeouts` branch of `refact-chat-js`
Relies on [#155](https://github.com/smallcloudai/refact-chat-js/pull/155)
=> Fix: CodeLens double-click & File Attachment

src/codeLens.ts
Open Chat codelens instruction no longer freezes execution of other instructions
=> fix: cleaning state up if codelens instruction doesn't contain message

src/estate.ts, src/sidebar.ts
Treats well of paths for direct file opening & rainbow animation is getting restored on Windows
Relies on this pull request from `refact-chat-js`:
https://github.com/smallcloudai/refact-chat-js/pull/160
=> Fix: Windows paths & Rainbow

src/codeLens.ts
Previously, if codelens instructions were containing flag `auto_submit` set to `false` - all other intents to click on codelens were prevented.
This pull request provides a fix of that unexpected behavior.
How to test?
- Step 1: Set codelens instructions to `auto_submit: false`, `new_tab: false`
- Step 2: Try to click Explain first
- Step 3: Try to click Find Problems then
Expected Result:
Text within textarea should be replaced by text of the instruction itself, codelens should not be frozen anymore.
=> Fix: Unfreezing CodeLens if auto_submit is set to false

src/quickProvider.ts
- Problem: Quick Actions are creating entirely new chat thread manually. Because of that, we are loosing selected by user model, agent capabilities, even tools. Also, if user clicks on "Find bugs", user's selection gets ignored, because it was relying only on range of code found as potential compilation errors (`vscode.Diagnostic[]`)
- Solution: Using the same approach, as CodeLens instructions use, sending to the client formatted message and then submitting the form with snippets, files and actual message attached. For bugs, checking if diagnostics are present, if yes, then relying on them, if not, taking user's lines selection to be working with later on.
- [💡 switches model back to 4o-mini, use the same method as codelens](https://refact.fibery.io/Software_Development/UI-VS-347#Task/swi …
=> Fix: Quick Actions commands execution

package.json, src/sidebar.ts
Adds memory management to vs-code.
Wait until this is reviewed / published.
https://github.com/smallcloudai/refact-chat-js/pull/196
requires the next alpha build of chat with the knowledge PR.
=> Chat features

package.json, src/sidebar.ts
wait for: https://github.com/smallcloudai/refact-chat-js/pull/345 to be merged
=> WIP: New patch functions
